name: Deploy Terraform

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.1
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup Workspace
        run: cd terraform
    
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
