name: Deploy Terraform

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.1

      - name: Setup Workspace
        run: cd terraform
    
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -out=tfplan
      #   working-directory: ./terraform

      # - name: Terraform Apply
      #   if: success()
      #   run: terraform apply -auto-approve tfplan
      #   working-directory: ./terraform

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin
          docker compose version

      - name: Start up Grafana and Prometheus
        run: |
          docker-compose -f ./docker/docker-compose.yml up -d
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
